[beta-updates] isolate_example
flutter/samples pull request #1198
Opened 2022-05-03 14:46 UTC by craiglabenz

Updated `isolate_example` for Dart 2.17

2022-05-03 21:30 UTC, domesticmouse requested changes

2022-05-03 21:30 UTC, domesticmouse commented on isolate_example/lib/performance_page.dart
> +  PerformancePageState createState() => PerformancePageState();
`State<PerformancePage> createState() => _PerformancePageState();`

2022-05-09 23:36 UTC, craiglabenz commented on isolate_example/lib/performance_page.dart
> +  PerformancePageState createState() => PerformancePageState();
Updated

2022-05-09 23:37 UTC, domesticmouse approved these changes

2022-05-10 00:21 UTC, merged