[beta-updates] platform_view_swift
flutter/samples pull request #1206
Opened 2022-05-03 17:17 UTC by craiglabenz

Updated `platform_view_swift` to Dart 2.17

2022-05-03 21:22 UTC, domesticmouse requested changes

2022-05-03 21:22 UTC, domesticmouse commented on platform_view_swift/lib/main.dart
> +  HomePageState createState() => HomePageState();
`State<HomePage> createState() => _HomePageState();`

2022-05-09 23:23 UTC, craiglabenz commented on platform_view_swift/lib/main.dart
> +  HomePageState createState() => HomePageState();
Updated

2022-05-09 23:28 UTC, domesticmouse approved these changes

2022-05-09 23:36 UTC, domesticmouse approved these changes

2022-05-10 00:06 UTC, merged