[beta-updates] veggieseasons
flutter/samples pull request #1210
Opened 2022-05-03 17:27 UTC by craiglabenz

Updated `veggieseasons` for Dart 2.17

2022-05-03 21:02 UTC, domesticmouse requested changes

2022-05-03 21:02 UTC, domesticmouse commented on veggieseasons/lib/screens/details.dart
> +  DetailsScreenState createState() => DetailsScreenState();
State<DetailsScreen> createState() => _DetailsScreenState();

2022-05-09 23:17 UTC, craiglabenz commented on veggieseasons/lib/screens/details.dart
> +  DetailsScreenState createState() => DetailsScreenState();
Updated

2022-05-09 23:37 UTC, domesticmouse commented on veggieseasons/lib/screens/search.dart
> +  SearchScreenState createState() => SearchScreenState();
Got another one =)

2022-05-09 23:38 UTC, domesticmouse commented on veggieseasons/lib/widgets/close_button.dart
> +  ColorChangingIconState createState() => ColorChangingIconState();
And another =)

2022-05-09 23:38 UTC, domesticmouse commented on veggieseasons/lib/widgets/trivia.dart
> +  TriviaViewState createState() => TriviaViewState();
Beep!

2022-05-09 23:38 UTC, domesticmouse commented on veggieseasons/lib/widgets/veggie_card.dart
> +  PressableCardState createState() => PressableCardState();
Beep beep!

2022-05-10 00:05 UTC, craiglabenz commented on veggieseasons/lib/widgets/veggie_card.dart
> +  PressableCardState createState() => PressableCardState();
Okay, looked for them all this time

2022-05-10 00:19 UTC, merged