Added Google Maps sample code
flutter/samples pull request #1671
Opened 2023-02-24 17:24 UTC by atsansone

2023-02-25 00:09 UTC, domesticmouse requested changes
Please add this project to the CI pipeline by editing the https://github.com/flutter/samples/blob/main/tool/flutter_ci_script_stable.sh, https://github.com/flutter/samples/blob/main/tool/flutter_ci_script_beta.sh, and https://github.com/flutter/samples/blob/main/tool/flutter_ci_script_master.sh scripts

2023-02-25 00:09 UTC, domesticmouse commented on google_maps/pubspec.yaml
> +# The following line prevents the package from being accidentally published to
Feel free to delete these comments. They add little value in this context.

2023-02-25 00:09 UTC, domesticmouse commented on google_maps/pubspec.yaml
> +dev_dependencies:
Please add a dependency on `analysis_defaults` as follows:

```yaml
dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
```

2023-02-25 00:09 UTC, domesticmouse commented on google_maps/analysis_options.yaml
> +include: ../../analysis_options.yaml
Please replace this line with the following:

```yaml
include: package:analysis_defaults/flutter.yaml
```

2023-02-27 20:06 UTC, atsansone reviewed
@domesticmouse : Updated!

2023-02-27 21:42 UTC, domesticmouse requested changes
Update the minSdk and add this directory to https://github.com/flutter/samples/blob/main/.github/dependabot.yaml to keep deps updated

2023-02-27 21:42 UTC, domesticmouse commented on google_maps/pubspec.yaml
> +  sdk: '>=2.18.5 <3.0.0'
2.19.0 minimum

2023-02-28 00:16 UTC, domesticmouse approved these changes

2023-02-28 00:16 UTC, merged

2023-02-28 00:17 UTC, domesticmouse commented
Thanks for doing this @atsansone!