Enable Material 3 on background_isolate_channels
flutter/samples pull request #1946
Opened 2023-07-20 11:43 UTC by miquelbeltran

Enabling Material 3

TODO: Add screenshots

## Pre-launch Checklist

- [ ] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [ ] I signed the [CLA].
- [ ] I read the [Contributors Guide].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

2023-07-20 23:37 UTC, domesticmouse commented
In Material 3 the search area is getting lost. Can we migrate to using the [Material 3 SearchBar](https://api.flutter.dev/flutter/material/SearchBar-class.html)? Here's a [nice intro tutorial](https://maneesha-erandi.medium.com/flutter-ui-essentials-material-3-searchbar-6c1acc540a2) by Maneesha Erandi.

2023-07-21 01:53 UTC, domesticmouse requested changes
Needs a M3 SearchBar

2023-07-24 12:09 UTC, miquelbeltran commented
<img width="912" alt="Screenshot 2023-07-24 at 13 57 41" src="https://github.com/flutter/samples/assets/2494376/0ed740d9-c47b-4437-a00b-be2de8d308f6">
<img width="912" alt="Screenshot 2023-07-24 at 13 57 34" src="https://github.com/flutter/samples/assets/2494376/3d6a39b8-161b-4388-b16b-d1bd378e25eb">

Replaced the Text edit with a `SearchBar`, moved to the `AppBar` bottom section, and simplified the body of the `Scaffold`

2023-07-24 18:49 UTC, domesticmouse approved these changes

2023-07-24 18:50 UTC, merged