[animations] adds test for AnimatedPositioned
flutter/samples pull request #576
Opened 2020-10-25 16:32 UTC by tusharojha

# Description
Adds widget test for `AnimatedPositioned`

In regard to issue #399

2020-10-30 18:26 UTC, RedBrogdon requested changes
One minor change requested. Thanks for adding a test!

2020-10-30 18:26 UTC, RedBrogdon commented on animations/test/misc/animated_positioned_test.dart
> +      // get initial position of the widget
nit: These comments are great, but wach should begin with a capital letter and end with a period.

2020-10-31 04:37 UTC, tusharojha commented
Thanks, @RedBrogdon. I have made the suggested changes.

2020-11-02 21:06 UTC, RedBrogdon approved these changes

2020-11-02 21:06 UTC, merged