[testing_app] added basic placeholder for favorites list
flutter/samples pull request #581
Opened 2020-11-01 20:08 UTC by tusharojha

## Description 

Added a simple placeholder message for the favorites list page.

Related Issue #578

2020-11-02 22:17 UTC, RedBrogdon requested changes
As I mentioned in the associated issue, this app mostly exists to show people how to write tests.

Now that you've added some additional functionality, it's a great opportunity to show how to test that functionality. Consider what kind of test you'd add to this file:

https://github.com/flutter/samples/blob/master/testing_app/test/favorites_test.dart#L31

To make sure the placeholder is correctly displayed when the favorites list is empty.

2020-11-03 07:01 UTC, tusharojha commented
I have added a test for checking if the placeholder shows up in the case of the empty favorites list.

Also, While I was going through other tests in the project I found a bit incorrect comment. Although, I haven't changed it since it's not discussed yet.

https://github.com/flutter/samples/blob/master/testing_app/test/models/favorites_test.dart#L14
It says _Generate a random number._ but currently, it's hardcoded to 35. Either we can change the comment or can actually generate a random number.

@RedBrogdon WDYT?

2020-11-04 11:23 UTC, abd99 commented
> Also, While I was going through other tests in the project I found a bit incorrect comment. Although, I haven't changed it since it's not discussed yet.
https://github.com/flutter/samples/blob/master/testing_app/test/models/favorites_test.dart#L14
It says Generate a random number. but currently, it's hardcoded to 35. Either we can change the comment or can actually generate a random number.

@tusharojha, thanks for mentioning this! I think I missed it while removing the usage of random numbers from the sample. You can remove that comment entirely. I've done the same mistake on [line 25](https://github.com/flutter/samples/blob/0c011574d015777b093fa1413ef70261310342bc/testing_app/test/models/favorites_test.dart#L25) as well. Can you please remove that too?

I should probably have a recheck on the entire sample once this PR gets merged. =)

2020-11-05 10:41 UTC, tusharojha commented
> Can you please remove that too?

Yes, of course.

> I should probably have a recheck on the entire sample once this PR gets merged. =)

Although I have gone through the entire code once but definitely a good idea that you also check it once.

2020-11-05 11:36 UTC, abd99 requested changes
Thanks for this PR @tusharojha!. I have left a few smalls nits. Other than that, all good.

2020-11-05 11:36 UTC, abd99 commented on testing_app/test/favorites_test.dart
> +      // Verify if Placeholder Text shows up.
nit:
```suggestion
      // Verify if the placeholder text shows up.
```

2020-11-05 11:36 UTC, abd99 commented on testing_app/lib/screens/favorites.dart
> +                child: Text('No Favorites Added'),
nit:
```suggestion
                child: Text('No favorites added.'),
```

2020-11-05 11:36 UTC, abd99 commented on testing_app/test/favorites_test.dart
> +      expect(find.text('No Favorites Added'), findsOneWidget);
nit:
```suggestion
      expect(find.text('No favorites added.'), findsOneWidget);
```

2020-11-05 19:18 UTC, tusharojha commented
Thanks, @abd99!
I am a bit new to these conventions but will take care of these in future commits.

2020-11-06 06:42 UTC, abd99 approved these changes
LGTM!

2020-11-13 22:16 UTC, RedBrogdon approved these changes

2020-11-13 22:16 UTC, merged

2020-11-13 22:16 UTC, RedBrogdon commented
Thanks, @tusharojha!